return (game) => {

	for (e of [
		'define_resource',
		'define_no_resource',
		'define_animation',
		'define_moraleset',
		'define_unit',
		'game_settings',
		'select_faction',
		'ready_or_not',
		'spawn_unit',
		'despawn_unit',
		'move_unit',
		'attack_unit',
		'advance_unit_after_combat',
		'unit_skip_turn',
		'terraform_tile',
		'cancel_terraform',
		'define_base_pop',
		'define_base_facility',
		'spawn_base',
		'found_base',
		'add_base_pop',
		'remove_base_pop',
		'process_base_growth',
		'refresh_base_psych',
		'set_base_production',
		'queue_base_production',
		'remove_base_production',
		'process_base_production',
		'hurry_base_production',
		'liquidate_base_facility',
		'initialize_player_research',
		'process_player_research',
		'settle_player_economy',
		'process_player_economy',
		'set_social_engineering',
		'declare_vendetta',
		'propose_diplomatic_relation',
		'respond_diplomatic_proposal',
		'propose_diplomatic_trade',
		'respond_diplomatic_trade',
		'propose_diplomatic_loan',
		'respond_diplomatic_loan',
		'process_diplomatic_loan_payment',
		'probe_operation',
		'fungal_bloom',
		'declare_victory',
		'complete_turn',
		'uncomplete_turn',
		'advance_turn',
		'chat_message',
		'work_base_tile',
		'unwork_base_tile',
	]) {
		game.register_event(e, #include('event/' + e));
	}

};
