#!/usr/bin/env python3
"""Generate compatibility catalogs from an original SMAC alpha.txt file."""

from __future__ import annotations

import argparse
import csv
import re
from dataclasses import dataclass
from pathlib import Path


TECHNOLOGY_ID_OVERRIDES = {
    "Secrets of the Human Brain": "SecretsHumanBrain",
}

TECHNOLOGY_COST_OVERRIDES = {
    "Biogenetics": 30,
    "IndustrialBase": 50,
    "InformationNetworks": 40,
    "AppliedPhysics": 50,
    "SocialPsych": 40,
    "DoctrineMobility": 30,
    "CentauriEcology": 20,
    "PlanetaryNetworks": 50,
    "DoctrineLoyalty": 60,
    "IndustrialEconomics": 70,
    "SecretsHumanBrain": 80,
}


@dataclass(frozen=True)
class TechnologyRow:
    name: str
    code: str
    prerequisite_codes: tuple[str, ...]


def canonical_id(name: str) -> str:
    if name in TECHNOLOGY_ID_OVERRIDES:
        return TECHNOLOGY_ID_OVERRIDES[name]
    expanded = name.replace("Adv.", "Advanced")
    words = re.findall(r"[A-Za-z0-9]+", expanded)
    return "".join(word[:1].upper() + word[1:] for word in words)


def read_section(path: Path, section: str) -> list[str]:
    lines = path.read_text(encoding="latin-1").splitlines()
    marker = f"#{section}"
    try:
        start = lines.index(marker) + 1
    except ValueError as exc:
        raise ValueError(f"{path} has no {marker} section") from exc
    result: list[str] = []
    for line in lines[start:]:
        if line.startswith("#"):
            break
        stripped = line.strip()
        if stripped and not stripped.startswith(";"):
            result.append(line)
    return result


def read_technologies(path: Path) -> list[TechnologyRow]:
    technologies: list[TechnologyRow] = []
    for line in read_section(path, "TECHNOLOGY"):
        row = next(csv.reader([line], skipinitialspace=True))
        if len(row) < 8:
            raise ValueError(f"invalid TECHNOLOGY row: {line}")
        name = row[0].strip()
        if name.lower() == "deleted" or name.startswith("User Technology "):
            continue
        prerequisite_codes = tuple(
            code for code in (row[6].strip(), row[7].strip()) if code != "None"
        )
        technologies.append(
            TechnologyRow(
                name=name,
                code=row[1].strip(),
                prerequisite_codes=prerequisite_codes,
            )
        )
    return technologies


def quote(value: str) -> str:
    return "'" + value.replace("\\", "\\\\").replace("'", "\\'") + "'"


def generate_technology_catalog(rows: list[TechnologyRow]) -> str:
    code_to_id: dict[str, str] = {}
    for row in rows:
        technology_id = canonical_id(row.name)
        if row.code in code_to_id:
            raise ValueError(f"duplicate technology code: {row.code}")
        if technology_id in code_to_id.values():
            raise ValueError(f"duplicate technology id: {technology_id}")
        code_to_id[row.code] = technology_id

    prerequisites: dict[str, tuple[str, ...]] = {}
    names: dict[str, str] = {}
    order: list[str] = []
    for row in rows:
        technology_id = code_to_id[row.code]
        try:
            prerequisite_ids = tuple(
                code_to_id[code] for code in row.prerequisite_codes
            )
        except KeyError as exc:
            raise ValueError(
                f"{technology_id} references missing technology code {exc.args[0]}"
            ) from exc
        prerequisites[technology_id] = prerequisite_ids
        names[technology_id] = row.name
        order.append(technology_id)

    tiers: dict[str, int] = {}
    resolving: set[str] = set()

    def get_tier(technology_id: str) -> int:
        if technology_id in tiers:
            return tiers[technology_id]
        if technology_id in resolving:
            raise ValueError(f"technology dependency cycle at {technology_id}")
        resolving.add(technology_id)
        prerequisite_ids = prerequisites[technology_id]
        tier = 0 if not prerequisite_ids else 1 + max(
            get_tier(prerequisite_id) for prerequisite_id in prerequisite_ids
        )
        resolving.remove(technology_id)
        tiers[technology_id] = tier
        return tier

    for technology_id in order:
        get_tier(technology_id)

    output = [
        "// Generated by tools/content/import_alpha.py from the original SMAC alpha.txt.",
        "// This catalog contains gameplay compatibility metadata only.",
        "const definitions = {",
    ]
    for technology_id in order:
        cost = TECHNOLOGY_COST_OVERRIDES.get(
            technology_id,
            20 + tiers[technology_id] * 10,
        )
        prerequisite_list = ", ".join(
            quote(prerequisite_id)
            for prerequisite_id in prerequisites[technology_id]
        )
        output.extend(
            [
                f"\t{technology_id}: {{",
                f"\t\tid: {quote(technology_id)},",
                f"\t\tname: {quote(names[technology_id])},",
                f"\t\tcost: {cost},",
                f"\t\tprerequisites: [{prerequisite_list}],",
                "\t},",
            ]
        )
    output.extend(
        [
            "};",
            "",
            "const order = [",
            *(f"\t{quote(technology_id)}," for technology_id in order),
            "];",
            "",
            "return {definitions: definitions, order: order};",
            "",
        ]
    )
    return "\n".join(output)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("--alpha", type=Path, required=True)
    parser.add_argument("--technologies-output", type=Path, required=True)
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    rows = read_technologies(args.alpha)
    output = generate_technology_catalog(rows)
    args.technologies_output.parent.mkdir(parents=True, exist_ok=True)
    args.technologies_output.write_text(output, encoding="ascii", newline="\n")
    print(f"wrote {len(rows)} technologies to {args.technologies_output}")


if __name__ == "__main__":
    main()
