IF ( NOT DEFINED GLSMAC_OUTPUT OR GLSMAC_OUTPUT STREQUAL "" )
	MESSAGE( FATAL_ERROR "GLSMAC_OUTPUT is required" )
ENDIF ()

SET( GLSMAC_COMMIT "unknown" )
IF (
	DEFINED GLSMAC_GIT_EXECUTABLE AND
	NOT GLSMAC_GIT_EXECUTABLE STREQUAL "" AND
	EXISTS "${GLSMAC_GIT_EXECUTABLE}" AND
	DEFINED GLSMAC_SOURCE_DIR AND
	NOT GLSMAC_SOURCE_DIR STREQUAL ""
)
	EXECUTE_PROCESS(
		COMMAND "${GLSMAC_GIT_EXECUTABLE}" -C "${GLSMAC_SOURCE_DIR}" rev-parse --short=8 HEAD
		RESULT_VARIABLE GLSMAC_GIT_RESULT
		OUTPUT_VARIABLE GLSMAC_GIT_COMMIT
		ERROR_QUIET
		OUTPUT_STRIP_TRAILING_WHITESPACE
	)
	STRING( LENGTH "${GLSMAC_GIT_COMMIT}" GLSMAC_GIT_COMMIT_LENGTH )
	IF (
		GLSMAC_GIT_RESULT EQUAL 0 AND
		GLSMAC_GIT_COMMIT_LENGTH EQUAL 8 AND
		GLSMAC_GIT_COMMIT MATCHES "^[0-9A-Fa-f]+$"
	)
		SET( GLSMAC_COMMIT "${GLSMAC_GIT_COMMIT}" )
	ENDIF ()
ENDIF ()

GET_FILENAME_COMPONENT( GLSMAC_OUTPUT_DIRECTORY "${GLSMAC_OUTPUT}" DIRECTORY )
FILE( MAKE_DIRECTORY "${GLSMAC_OUTPUT_DIRECTORY}" )
SET( GLSMAC_HEADER "#pragma once\n#define GLSMAC_LAST_COMMIT \"${GLSMAC_COMMIT}\"\n" )

SET( GLSMAC_CURRENT_HEADER "" )
IF ( EXISTS "${GLSMAC_OUTPUT}" )
	FILE( READ "${GLSMAC_OUTPUT}" GLSMAC_CURRENT_HEADER )
ENDIF ()
IF ( NOT GLSMAC_CURRENT_HEADER STREQUAL GLSMAC_HEADER )
	FILE( WRITE "${GLSMAC_OUTPUT}" "${GLSMAC_HEADER}" )
ENDIF ()
